export type Vehicle = {
  lotNumber: string;
  vin: string;
  titleCode: string;
  odometer: string;
  color: string;
  primaryDamage: string;
  secondaryDamage: string;
  estimatedRepairCost: number;
  estimatedValue: number;
  engine: string;
  transmission: string;
  driveType: string;
  vehicleType: string;
  fuelType: string;
  hasKeys: true;
  details: string;
  offerStatus: string;
  saleStatus: string;
  currentOffer: number;
  buyNowPrice: number;
  maximumOffer: number;
  maximumBid: number;
  cubanAuctionFee: number;
  tutorialFee: number;
  virtualOfferFee: number;
  copartFee: number;
  gateFee: number;
  environmentalFee: number;
  transferFee: number;
  titleDeliveryFee: number;
  totalCost: number;
  auctionLocation: string;
  saleDate: string;
  auction: string;
  laneAndItem: string;
  lastUpdate: string;
};

export type SearchResults = Vehicle[];
